# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Vixasol.DogdouSpec
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - dogdouspec
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/XueYeHuLabs/dogdouspec/releases/download/v1.0.0/dogdouspec-win-x64.zip
    InstallerSha256: 0000000000000000000000000000000000000000000000000000000000000000
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: dogdouspec.exe
        PortableCommandAlias: dogdouspec
ManifestType: installer
ManifestVersion: 1.6.0