<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DogdouSpec.Cli</RootNamespace>
    <AssemblyName>dogdouspec</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DogdouSpec.Core\DogdouSpec.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>

</Project>
