<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DogdouSpec.Cli</RootNamespace>
    <AssemblyName>dogdouspec</AssemblyName>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Size</OptimizationPreference>
    <PublishTrimmed>true</PublishTrimmed>
    <DebuggerSupport>false</DebuggerSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <MetadataUpdateSupport>false</MetadataUpdateSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DogdouSpec.Core\DogdouSpec.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>

</Project>
